# TownyRaider Configuration

# General plugin settings
general:
  debug: false
  metrics: true

# Raid settings
raids:
  # Timing settings (cron expression format or specific times)
  schedule:
    enabled: true
    # Use either cron or fixed times
    use-cron: false
    # Cron expression (minute hour day-of-month month day-of-week)
    cron: "0 */3 * * *"  # Every 3 hours at the start of the hour
    # Fixed times (24-hour format)
    fixed-times:
      - "12:00"
      - "18:00"
      - "00:00"
  
  # Raid conditions
  conditions:
    minimum-online-town-members: 1
    maximum-chunk-distance: 5
    minimum-town-wealth: 1000
    minimum-town-age-days: 1
    
  # Raid duration in minutes
  duration: 10
  
  # Cooldown between raids for the same town (in hours)
  town-cooldown: 24
  
  # Maximum number of stolen items for boss bar progress
  max-stolen-items: 20
  
  # Visual effects
  effects:
    # Enable/disable glow effect for raiders
    glow-enabled: true
    
    # Enable/disable border effects
    border-effects-enabled: true
    
    # Enable/disable boss bar
    bossbar-enabled: true
    
    # Enable/disable stealing effects
    steal-effects-enabled: true

# Raid difficulty scaling settings
difficulty-scaling:
  base-zombie-count: 2
  base-skeleton-per-zombie: 2
  base-health-multiplier: 1.0
  base-speed-multiplier: 1.0
  base-damage-multiplier: 1.0
  base-raid-duration: 20
  wealth-scaling-factor: 0.00001
  resident-scaling-factor: 0.05
  land-scaling-factor: 0.02
  history-scaling-factor: 0.1
  max-zombie-count: 6
  max-skeleton-count: 12

# Mob settings
mobs:
  baby-zombie:
    name: "<gradient:red:dark_red><bold>Towny Plunderer</bold></gradient> <dark_gray>[Raider]</dark_gray>"
    health: 10
    speed: 0.3
    steal-delay: 20
    max-steals: 5
    glow-color: "RED"
  
  skeleton:
    name: "<gradient:#C0C0C0:#696969><bold>Shadow Archer</bold></gradient> <dark_gray>[Guardian]"
    health: 30.0
    speed: 0.25
    damage: 3.0
    count-per-zombie: 2
    ranks:
      novice:
        weight: 70
        gradient: "#C0C0C0:#696969"
        title: "Shadow Archer"
        color: "dark_gray"
        display: "Novice" 
        health_multiplier: 1.0
        speed_multiplier: 1.0
        damage_multiplier: 1.0
        resistance_level: 1
        rank_particle: "SMOKE_NORMAL"
      
      elite:
        weight: 25
        gradient: "#8A2BE2:#4B0082"
        title: "Void Sentinel"
        color: "dark_purple"
        display: "Elite"
        health_multiplier: 1.5
        speed_multiplier: 1.2
        damage_multiplier: 1.3
        resistance_level: 2
        fire_arrows: true
        rank_particle: "SPELL_WITCH"
      
      master:
        weight: 5
        gradient: "#FFD700:#FF4500"
        title: "Ancient Guardian"
        color: "gold"
        display: "Master"
        health_multiplier: 2.2
        speed_multiplier: 1.4
        damage_multiplier: 1.6
        resistance_level: 3
        fire_arrows: true
        rank_particle: "FLAME"

# Blocks and items that can be stolen
stealable:
  blocks:
    - "DIAMOND_BLOCK"
    - "GOLD_BLOCK"
    - "EMERALD_BLOCK"
    - "IRON_BLOCK"
    - "NETHERITE_BLOCK"
  
  # Maximum number of items per category to steal from chests
  chest-stealing:
    enabled: true
    valuable-items:
      - "DIAMOND"
      - "EMERALD"
      - "GOLD_INGOT"
      - "IRON_INGOT"
      - "NETHERITE_INGOT"
    max-items-per-category: 5

# Notification settings
notifications:
  # Time before raid in minutes to send warning
  pre-raid-warning: 5
  
  # Notification radius (in chunks)
  radius: 3
  
  # Sound effects
  sounds:
    pre-raid: "ENTITY_WITHER_SPAWN"
    raid-start: "ENTITY_ENDER_DRAGON_GROWL"
    raid-end: "ENTITY_PLAYER_LEVELUP"

# Messages (using MiniMessage format)
messages:
  prefix: "<dark_red>[<gold>TownyRaider<dark_red>]</gold> "
  pre-raid-warning: "<bold><red>WARNING!</red></bold> Your town will be raided in {minutes} minutes!"
  raid-start: "<dark_red>⚔ <bold>RAID STARTED!</bold> ⚔ <gold>Defend your town from the raiders!</gold>"
  raid-end: "<green>⚔ <bold>THE RAID HAS ENDED!</bold> ⚔</green> Your town {status}."
  raid-successful: "<red>was plundered</red>"
  raid-defended: "<green>was successfully defended</green>"
  no-permission: "<red>You don't have permission to use this command. Required: {permission}</red>"
  unknown-command: "<red>Unknown command: {command}</red>"
  config-reloaded: "<green>Configuration reloaded successfully!</green>"
  raid-status: "Raid status information will be shown here"
  raids-toggled: "<yellow>Raid functionality has been toggled</yellow>"
  help-header: "<gold>----- TownyRaider Help (v{version}) -----</gold>"
  help-command: "<yellow>{command}</yellow> - <gray>{description}</gray>"
  help-footer: "<gold>-----------------------------</gold>"
  status-header: "<yellow>Raid Status: <green>{enabled}</green> | Active Raids: <gold>{active_count}</gold></yellow>"
  status-raid: "<gray>Town: <white>{town}</white> | Started: <white>{start_time}</white> | Items Stolen: <red>{stolen}</red></gray>"
  status-no-raids: "<gray>No active raids at the moment.</gray>"
  raids-toggled: "<yellow>Raid functionality has been {status}.</yellow>"
  raid-bossbar-title: "<bold><dark_red>⚠ RAID IN PROGRESS: </dark_red> <gold>{town} under attack!</gold> <dark_red>⚠</dark_red></bold>"
  raid-protection-block-break: "<red>This block is protected during the raid!"
  raid-protection-block-place: "<red>You cannot place blocks in this area during a raid!"
  entering-raid-zone: "<dark_red>⚠ <red>You are entering an area under raid!"
  economy-raid-reward: "<green>⚔ <bold>DEFENSE REWARD!</bold> ⚔ The town treasury of <yellow>{town}</yellow> has been enriched with <gold>{amount}</gold> gold for your brave defense!"
  economy-raid-penalty: "<red>☠ <bold>RAID LOSSES!</bold> ☠ <yellow>{town}</yellow> has suffered damages of <gold>{amount}</gold> gold due to stolen resources."
  economy-raid-compensation: "<yellow>⚒ <bold>COMPENSATION:</bold> ⚒ You've received <gold>{amount}</gold> gold from the town treasury to rebuild after the raid."
  economy-defender-bonus: "<aqua>✦ <bold>HERO'S REWARD:</bold> ✦ For your bravery in defending <yellow>{town}</yellow>, you've earned <gold>{amount}</gold> gold!"
  # Admin command messages
  admin-command-usage: "<yellow>Usage: <white>{usage}</white></yellow>"
  admin-town-not-found: "<red>Town '{town}' not found!</red>"
  admin-raid-already-active: "<red>There is already an active raid on {town}!</red>"
  admin-raid-started: "<green>⚔ <bold>RAID INITIATED:</bold> ⚔ Raid on <gold>{town}</gold> has been started by <yellow>{admin}</yellow>."
  admin-raid-failed: "<red>Failed to start raid on {town}. Check console for details.</red>"
  admin-no-active-raids: "<yellow>There are no active raids at the moment.</yellow>"
  admin-all-raids-stopped: "<green>⚔ <bold>RAIDS HALTED:</bold> ⚔ <yellow>{count}</yellow> raids have been stopped by <gold>{admin}</gold>."
  admin-raid-not-found: "<red>There is no active raid on {town}!</red>"
  admin-raid-stopped: "<green>⚔ <bold>RAID STOPPED:</bold> ⚔ Raid on <gold>{town}</gold> has been halted by <yellow>{admin}</yellow>."
  admin-economy-reloaded: "<green>Economy settings have been reloaded.</green>"
  admin-economy-invalid-setting: "<red>Invalid economy setting: {setting}</red>"
  admin-economy-invalid-value: "<red>Invalid value: {value}. Please use a numeric value.</red>"
  admin-economy-updated: "<green>Economy setting '{setting}' updated to {value}.</green>"
  admin-economy-settings-header: "<yellow>Current Economy Settings:</yellow>"
  admin-economy-setting: "<gray>- {setting}: <white>{value}</white></gray>"
  admin-economy-settings-footer: "<yellow>Use /townyraider admin economy <setting> <value> to change a setting.</yellow>"
  admin-player-only-command: "<red>This command can only be used by players.</red>"
  admin-debug-invalid-option: "<red>Invalid debug option: {option}</red>"
  admin-debug-toggled: "<yellow>Debug mode {status}.</yellow>"
  admin-debug-raids-header: "<yellow>Active Raids Debug Info:</yellow>"
  admin-debug-raid-info: "<gray>Town: <white>{town}</white> | ID: <white>{id}</white> | Started: <white>{start}</white> | Stolen: <white>{stolen}</white> | Raiders: <white>{raiders}</white></gray>"
  admin-debug-town-header: "<yellow>Town Debug Info: <white>{town}</white></yellow>"
  admin-debug-town-economy: "<gray>Rewards: <green>{rewards}</green> | Penalties: <red>{penalties}</red> | Net: <white>{net}</white></gray>"
  admin-debug-economy-header: "<yellow>Economy Debug Info:</yellow>"
  admin-debug-economy-info: "<gray>Enabled: <white>{enabled}</white> | Base Item Value: <white>{base_item_value}</white> | Base Reward: <white>{raid_base_reward}</white> | Base Penalty: <white>{raid_base_penalty}</white></gray>"
  admin-debug-location-header: "<yellow>Location Debug Info:</yellow>"
  admin-debug-location-info: "<gray>World: <white>{world}</white> | X: <white>{x}</white> | Y: <white>{y}</white> | Z: <white>{z}</white> | Town: <white>{in_town}</white> | Under Raid: <white>{under_raid}</white></gray>"
  admin-unknown-command: "<red>Unknown admin command: {command}</red>"
  admin-help-header: "<gold>====== TownyRaider Admin Commands ======</gold>"
  admin-help-footer: "<gold>=====================================</gold>"

# Protection settings
protection:
  # Radius around raid location that gets special protection (in blocks)
  raid-protection-radius: 50
  
  # Whether to provide defense bonuses during raids
  enable-defense-bonus: true
  
  # Materials that are protected during raids (can only be broken by raid mobs)
  protected-materials:
    - "CHEST"
    - "BARREL"
    - "FURNACE"
    - "BLAST_FURNACE"
    - "SMOKER"
    - "BREWING_STAND"
    - "ENCHANTING_TABLE"
    - "BEACON"
    - "ANVIL"
    - "LODESTONE"
    - "DISPENSER"
    - "DROPPER"
    - "HOPPER"
    - "SHULKER_BOX"
  
  # Materials that players can place during raids for defense
  defensive-blocks:
    - "COBBLESTONE"
    - "DIRT"
    - "STONE"
    - "OAK_PLANKS"
    - "SPRUCE_PLANKS"
    - "BIRCH_PLANKS"
    - "JUNGLE_PLANKS"
    - "ACACIA_PLANKS"
    - "DARK_OAK_PLANKS"
    - "FENCE"
    - "OAK_FENCE"
    - "IRON_BARS"

# Economy settings
economy:
  # Base value for each stolen item
  base-item-value: 50.0
  
  # Base reward for successfully defending a town
  raid-base-reward: 500.0
  
  # Base penalty for losing a raid
  raid-base-penalty: 300.0
  
  # Multiplier for raid rewards (baseReward * multiplier)
  raid-reward-multiplier: 1.0
  
  # Multiplier for stolen items when calculating penalties (basePenalty + (stolenValue * multiplier))
  raid-penalty-multiplier: 0.5
  
  # Maximum percentage of a town's balance that can be taken as a penalty
  max-penalty-percentage: 0.1
  
  # Bonus given to each player who actively defended the town
  defender-bonus: 100.0
  
  # Whether to give bonus rewards to town defenders
  defender-bonus-enabled: true
  
  # Whether to compensate players when items are stolen
  defender-compensation-enabled: true
  
  # Multiplier for compensation (stolenValue * multiplier / playerCount)
  compensation-multiplier: 0.3